url: https://shaungeorge.github.io/shema.github.io/
baseurl: /shema.github.io/

# Site settings
title: Shemas site
email: admin@shema.com
description: "Test description."


# Team names, titles and social links
people:
- name: Shemas
  pic: 
  position: Photographer
  social:
    - title: twitter
      url: #
    - title: instagram
      url: #
    - title: tiktok
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: instagram
    url:
  - title: tiktok
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: America

# Build settings
markdown: kramdown
permalink: pretty